package com.flavor_immersed_daily.datagen.tag;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

/** Item-tag keys generated by {@link FIDItemTagsProvider}. */
public final class FIDItemTags {
    public static final TagKey<Item> RADISH = create("radish");
    public static final TagKey<Item> SEASONING = create("seasoning");
    public static final TagKey<Item> SEEDS = create("seeds");
    public static final TagKey<Item> BLOOD = create("blood");
    public static final TagKey<Item> CHICKEN = create("chicken");
    public static final TagKey<Item> MEAT = create("meat");

    private FIDItemTags() {
    }

    private static TagKey<Item> create(String name) {
        return TagKey.create(Registries.ITEM, ResourceLocation.fromNamespaceAndPath("fid", name));
    }
}
